/-
The double antisymmetrizer on the vectorization index.

The vectorization of an operator on `U ⊗ V` carries four tensor factors, in the
order `(U_out, V_out, U_in, V_in)`.  The Fu-Gao-Park antisymmetrized pairs are
`(U_out, U_in)` and `(V_out, V_in)`; the corresponding index involutions are
`swU` and `swV`, and `Qm` is the orthogonal projection onto the subspace
antisymmetric under both.  Its defining property is that it acts as the identity
on `vec K` for every `K ∈ so(U) ⊗ so(V)`.
-/
import RankR.Skew
import RankR.Kraus

namespace RankR

open Matrix Finset ComplexConjugate
open scoped Kronecker

/-- The index type of the vectorization of an operator on `U ⊗ V`, read as the
four tensor factors `(U_out, V_out, U_in, V_in)`. -/
abbrev Idx (U V : Type*) : Type _ := (U × V) × (U × V)

section Antisym

variable {U V : Type*} [Fintype U] [Fintype V] [DecidableEq U] [DecidableEq V]

/-! ## The two factor swaps -/

omit [Fintype U] [Fintype V] [DecidableEq U] [DecidableEq V] in
/-- Exchange of the two `U` slots, that is of tensor factors `1` and `3`,
leaving the two `V` slots in place. -/
def swU : Idx U V → Idx U V := fun p => ((p.2.1, p.1.2), (p.1.1, p.2.2))

omit [Fintype U] [Fintype V] [DecidableEq U] [DecidableEq V] in
/-- Exchange of the two `V` slots, that is of tensor factors `2` and `4`,
leaving the two `U` slots in place. -/
def swV : Idx U V → Idx U V := fun p => ((p.1.1, p.2.2), (p.2.1, p.1.2))

omit [Fintype U] [Fintype V] [DecidableEq U] [DecidableEq V] in
/-- `swU` is an involution. -/
@[simp] theorem swU_swU (p : Idx U V) : swU (swU p) = p := rfl

omit [Fintype U] [Fintype V] [DecidableEq U] [DecidableEq V] in
/-- `swV` is an involution. -/
@[simp] theorem swV_swV (p : Idx U V) : swV (swV p) = p := rfl

omit [Fintype U] [Fintype V] [DecidableEq U] [DecidableEq V] in
/-- The two swaps act on disjoint pairs of tensor factors, hence commute. -/
@[simp] theorem swU_swV (p : Idx U V) : swU (swV p) = swV (swU p) := rfl

omit [Fintype U] [Fintype V] [DecidableEq U] [DecidableEq V] in
/-- The composite `swV ∘ swU`, the simultaneous exchange of both pairs, is an
involution. -/
theorem swVU_swVU (p : Idx U V) : swV (swU (swV (swU p))) = p := rfl

/-- For an involution `f`, the equation `X = f Y` is symmetric in `X` and `Y`. -/
private theorem eq_involutive_comm {α : Type*} {f : α → α} (hf : ∀ x, f (f x) = x)
    {X Y : α} : (X = f Y) ↔ (Y = f X) := by
  constructor <;> · rintro rfl; rw [hf]

/-! ## The double antisymmetrizer -/

omit [Fintype U] [Fintype V] in
/-- The double antisymmetrizer `(1 - S_U)(1 - S_V) / 4`, where `S_U` and `S_V`
are the permutation matrices of `swU` and `swV`. -/
noncomputable def Qm : Matrix (Idx U V) (Idx U V) ℂ :=
  Matrix.of fun X Y =>
    (4 : ℂ)⁻¹ * ((if Y = X then 1 else 0) - (if Y = swU X then 1 else 0)
               - (if Y = swV X then 1 else 0) + (if Y = swV (swU X) then 1 else 0))

omit [Fintype U] [Fintype V] in
/-- The entries of `Qm`. -/
@[simp] theorem Qm_apply (X Y : Idx U V) :
    Qm X Y = (4 : ℂ)⁻¹ * ((if Y = X then 1 else 0) - (if Y = swU X then 1 else 0)
               - (if Y = swV X then 1 else 0) + (if Y = swV (swU X) then 1 else 0)) := rfl

/-- The action of `Qm` on a vector is the normalized alternating sum over the
Klein four-group generated by `swU` and `swV`. -/
theorem mulVecE_Qm (v : EuclideanSpace ℂ (Idx U V)) (X : Idx U V) :
    mulVecE Qm v X = (4 : ℂ)⁻¹ * (v X - v (swU X) - v (swV X) + v (swV (swU X))) := by
  rw [mulVecE_apply]
  have hterm : ∀ Y : Idx U V, Qm X Y * v Y
      = (4 : ℂ)⁻¹ * ((if Y = X then v Y else 0) - (if Y = swU X then v Y else 0)
          - (if Y = swV X then v Y else 0) + (if Y = swV (swU X) then v Y else 0)) := by
    intro Y
    rw [Qm_apply]
    split_ifs <;> ring
  simp only [hterm, ← Finset.mul_sum, Finset.sum_add_distrib, Finset.sum_sub_distrib,
    Finset.sum_ite_eq', Finset.mem_univ, if_true]

omit [Fintype U] [Fintype V] in
/-- `Qm` is self-adjoint: its entries are real and the four index conditions are
symmetric, because `swU`, `swV` and `swV ∘ swU` are involutions. -/
theorem Qm_conjTranspose : (Qm (U := U) (V := V))ᴴ = Qm := by
  ext X Y
  have h1 : (X = Y) ↔ (Y = X) := eq_comm
  have h2 : (X = swU Y) ↔ (Y = swU X) := eq_involutive_comm swU_swU
  have h3 : (X = swV Y) ↔ (Y = swV X) := eq_involutive_comm swV_swV
  have h4 : (X = swV (swU Y)) ↔ (Y = swV (swU X)) :=
    eq_involutive_comm (f := fun p : Idx U V => swV (swU p)) swVU_swVU
  rw [Matrix.conjTranspose_apply, Qm_apply, Qm_apply]
  simp only [h1, h2, h3, h4, star_mul', star_sub, star_add, apply_ite (star : ℂ → ℂ),
    star_one, star_zero]
  norm_num

/-- `Qm` is idempotent, hence an orthogonal projection. -/
theorem Qm_mul_self : (Qm (U := U) (V := V)) * Qm = Qm := by
  ext X Y
  have key : (Qm * Qm : Matrix (Idx U V) (Idx U V) ℂ) X Y
      = mulVecE Qm (WithLp.toLp 2 fun Z : Idx U V => Qm Z Y) X := rfl
  rw [key, mulVecE_Qm]
  simp only [Qm_apply, swU_swU, swV_swV, swU_swV]
  split_ifs <;> ring

/-! ## Invariance of the double-skew subspace -/

omit [DecidableEq U] [DecidableEq V] in
private theorem mulVecE_zero (A : Matrix (Idx U V) (Idx U V) ℂ) : mulVecE A 0 = 0 := by
  ext p
  simp [mulVecE_apply]

omit [DecidableEq U] [DecidableEq V] in
private theorem mulVecE_add (A : Matrix (Idx U V) (Idx U V) ℂ)
    (x y : EuclideanSpace ℂ (Idx U V)) : mulVecE A (x + y) = mulVecE A x + mulVecE A y := by
  ext p
  simp [mulVecE_apply, mul_add, Finset.sum_add_distrib]

omit [DecidableEq U] [DecidableEq V] in
private theorem mulVecE_smul (c : ℂ) (A : Matrix (Idx U V) (Idx U V) ℂ)
    (x : EuclideanSpace ℂ (Idx U V)) : mulVecE A (c • x) = c • mulVecE A x := by
  ext p
  simp [mulVecE_apply, Finset.mul_sum, mul_left_comm]

omit [Fintype U] [Fintype V] [DecidableEq U] [DecidableEq V] in
private theorem vec_zero' {m n : Type*} [Fintype m] [Fintype n] :
    vec (0 : Matrix m n ℂ) = 0 := by
  ext p
  simp [vec]

omit [Fintype U] [Fintype V] [DecidableEq U] [DecidableEq V] in
private theorem vec_add' {m n : Type*} [Fintype m] [Fintype n] (A B : Matrix m n ℂ) :
    vec (A + B) = vec A + vec B := by
  ext p
  simp [vec]

omit [Fintype U] [Fintype V] [DecidableEq U] [DecidableEq V] in
private theorem vec_smul' {m n : Type*} [Fintype m] [Fintype n] (c : ℂ) (A : Matrix m n ℂ) :
    vec (c • A) = c • vec A := by
  ext p
  simp [vec]

/-- `Qm` fixes the vectorization of every double-skew operator.

On a generator `L ⊗ₖ M` with `Lᵀ = -L` and `Mᵀ = -M`, each of the two swaps
contributes a sign `-1` and the double swap a sign `+1`, so the alternating sum
of `mulVecE_Qm` has all four terms equal and the normalization `4⁻¹` restores
the original entry.  The property is linear in `K`, hence passes to the span. -/
theorem mulVecE_Qm_vec {K : Matrix (U × V) (U × V) ℂ} (hK : K ∈ doubleSkew U V) :
    mulVecE Qm (vec K) = vec K := by
  rw [doubleSkew] at hK
  induction hK using Submodule.span_induction with
  | mem x hx =>
      obtain ⟨L, M, hL, hM, rfl⟩ := hx
      have hL' : ∀ i j, L j i = -L i j := fun i j => by
        simpa using congrArg (fun A : Matrix U U ℂ => A i j) hL
      have hM' : ∀ i j, M j i = -M i j := fun i j => by
        simpa using congrArg (fun A : Matrix V V ℂ => A i j) hM
      ext X
      obtain ⟨⟨a, b⟩, a', b'⟩ := X
      rw [mulVecE_Qm]
      simp only [swU, swV, vec_apply, Matrix.kroneckerMap_apply]
      rw [hL' a a', hM' b b']
      ring
  | zero => rw [vec_zero', mulVecE_zero]
  | add x y _ _ hx hy => rw [vec_add', mulVecE_add, hx, hy]
  | smul a x _ hx => rw [vec_smul', mulVecE_smul, hx]

end Antisym

end RankR
